version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telecom
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      FLASK_APP: "app:create_app()"
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:password@db:5432/telecom
    ports:
      - "5000:5000"
